name: Android Continuous Deployment

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github Actions
        uses: actions/checkout@v2

      - name: Set Up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'zulu'

      - name: Show Java Version
        run: java --version

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Build Apps With Gradle
        run: ./gradlew assembleRelease
