name: Android Continuous Integration

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github Actions
        uses: actions/checkout@v2

      - name: Set Up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'zulu'

      - name: Show Java Version
        run: java --version

      - name: Set Up NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
          add-to-path: true

      - name: Show NDK Version
        run: ndk-build --version

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Build Apps With Gradle
        run: ./gradlew assembleDebug
